apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  template:
    metadata:
      name: spark-job
    spec:
      restartPolicy: Never
      containers:
      - name: spark-job
        image: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_NAME }}:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: spark-job-config
        command: ["/opt/entrypoint.sh"]
        args:
        - "driver"
        - "--master"
        - "${{ secrets.KUBERNETES_MASTER}}"
        - "--deploy-mode"
        - "client"
        - "--name"
        - "spark-job"
        - "--conf"
        - "spark.kubernetes.container.image=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_NAME }}:latest"
        - "--conf"
        - "spark.executor.instances=1"
        - "--conf"
        - "spark.driver.memory=3g"
        - "--conf"
        - "spark.executor.memory=3g"
        - "--conf"
        - "spark.driver.cores=2"
        - "--conf"
        - "spark.executor.cores=2"
        - "local:///opt/main/main.py"
      imagePullSecrets:
      - name: ${{ secrets.ACR_SECRET_NAME }}
