apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job4
  namespace: default
spec:
  template:
    metadata:
      name: spark-job4
      labels:
        app: spark-job4
    spec:
      containers:
      - name: spark-job4
        image: odare179/myspark2:latest  # Docker Hub image reference
        imagePullPolicy: IfNotPresent
        command: ["/opt/entrypoint.sh"]
        args:
        - "driver"
        - "--master"
        - "k8s://https://kubernetes.default.svc:443"
        - "--deploy-mode"
        - "cluster"
        - "--name"
        - "spark-job4"
        - "--conf"
        - "spark.kubernetes.container.image=odare179/myspark2:latest"  # Docker Hub image reference
        - "--conf"
        - "spark.executor.instances=1"
        - "--conf"
        - "spark.driver.memory=8g"
        - "--conf"
        - "spark.executor.memory=8g"
        - "--conf"
        - "spark.driver.cores=2"
        - "--conf"
        - "spark.executor.cores=2"
        # - "--conf"
        # - "spark.dynamicAllocation.shuffleTracking.enabled=true"
        - "--conf"
        - "spark.kubernetes.namespace=default"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.azure_client_id=azure-secrets:azure_client_id"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.azure_client_secret=azure-secrets:azure_client_secret"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.azure_storage_account=azure-secrets:azure_storage_account"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.azure_tenant_id=azure-secrets:azure_tenant_id"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.geocode_key=azure-secrets:geocode_key"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.hotels_path=azure-secrets:hotels_path"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.output_file_path=azure-secrets:output_file_path"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.sampling_fraction=azure-secrets:sampling_fraction"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.storage_container=azure-secrets:storage_container"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.weather_path=azure-secrets:weather_path"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.output_storage_account=azure-secrets:output_storage_account"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.output_storage_account_key=azure-secrets:output_storage_account_key"
        - "--conf"
        - "spark.kubernetes.driver.secretKeyRef.output_storage_container=azure-secrets:output_storage_container"
        - "local:///opt/main/main.py"
      restartPolicy: Never
  backoffLimit: 3
