name: Build and deploy an app to AKS

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
      # Debugging step to list directories in the repository root
      - name: List directories in repository root
        run: ls -alh ${{ github.workspace }}

      # Debugging step to list files in the k8s directory
      - name: List files in k8s directory
        run: ls -alh ${{ github.workspace }}/k8s

      # Debugging step to list files in the kubeconfig directory
      - name: List kubeconfig directory
        run: ls -alh /home/runner/work/_temp

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ github.workspace }}/k8s/deployment.yml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_NAME }}:latest
#      # Debugging step to list files in the root directory
#      - name: List files in root directory
#        run: ls -alh /
#
#          # Debugging step to list files in the k8s directory
#               - name: List files in k8s directory
#               run: ls -alh ${{ github.workspace }}/k8s
#
#      # Deploys application based on given manifest file
#      - name: Deploys application
#        uses: Azure/k8s-deploy@v4
#        with:
#          action: deploy
#          manifests: ./../../k8s/deployment.yml
#          images: |
#            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_NAME }}:latest

      # Debugging step to list files in the kubeconfig directory
#      - name: List kubeconfig directory
#        run: ls -alh /home/runner/work/_temp
#
#      - name: Deploys application
#        uses: Azure/k8s-deploy@v4
#        with:
#          action: deploy
#          manifests: ./../../k8s/deployment.yml
#
#          images: |
#            ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ secrets.CONTAINER_NAME }}:latest
